### PR TITLE
Dotnet maui workshop mvpvm

### PR DESCRIPTION
**Pull request by BillKrat**
Added section 7 MVP-VM to dotnet-maui-workshop.  In section 7, I demonstrate how this decoupled framework pattern can be used to easily reuse view models, views, and commands between multiple features, i.e., Monkey Finder and Furniture Inventory [new].   Using event aggregation the Monkey Finder publishes events handled by the Inventory application to keep both synchronized to the current connectivity status - updating the data as applicable (online/offline).

GitHub: https://github.com/BillKrat/dotnet-maui-workshop/tree/dotnet-maui-workshop-mvpvm/Part%207%20-%20MVPVM
Blog: http://www.adventuresontheedge.net/post/2022/07/05/MAUI-MvpVm

### CODE REVIEW

**Comment by jongalloway** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-presentations/dotnet-maui-workshop?pullRequest=75) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-presentations/dotnet-maui-workshop?pullRequest=75) before we can accept your contribution.<br/><br/>:x: BillKrat [sign now](https://cla.dotnetfoundation.org/dotnet-presentations/dotnet-maui-workshop?pullRequest=75)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-presentations/dotnet-maui-workshop?pullRequest=75) it.</sub>

**Comment by jamesmontemagno** [comment]
Hey Bill, thanks for the PR and for looking to add MVP into the mix. For this workshop I don't want to introduce another module into the main flow at this time as I have a full content plan. However, I would like to add on "Community Modules" in a new folder in which you can take the finished app and add something to it to teach developers a new topic. This would be a good candidate for this.

**Comment by jamesmontemagno** [comment]
I just created a guide: https://github.com/dotnet-presentations/dotnet-maui-workshop/blob/main/Community%20Modules/README.md

**Comment by BillKrat** [comment]
Thanks for the feedback, sounds good.  Please keep me in mind when the community module(s) are available.  

I remember when P&P released Prism and the Unity container (later MEF), I was totally lost as to how decoupled applications worked. Fell in love with them (still follow principles learned today) but found they are not embraced; teams prefer more conventional approach (you can follow the code).  

I’ve been painted into corners because of it, so this is my opportunity to get on a soapbox and sell the power of decoupled architectures based on IOC and talk is cheap.
 
Best regards
Bill

**Comment by jamesmontemagno** [comment]
@BillKrat take a look at https://github.com/dotnet-presentations/dotnet-maui-workshop/blob/main/Community%20Modules/README.md and let me know if that stuff makes sense

**Comment by BillKrat** [comment]
@James, makes sense, I’ll get the ball rolling this weekend.

**Pull request closed without merging**
